### ISSUE TITLE
Sub-Applications

### ISSUE THREAD

**Issue by lukeed** [lukeed/polka#1]
- Change `handler` signature to take `info` parameter again instead of `next`
- Move `501` check to `this.server` initializer instead of `handler`
- [Maybe] Rework `use()` to accept a pathname filter

**Comment by developit** [comment]
Would it be worth exposing this as `{ Router }`, or is that just duplicative?

**Comment by lukeed** [comment]
Wouldn't really make sense since the entirety of Polka _is_ the Router.

Allowing that import would just be for compatibility, but I might be okay avoiding that since no packaged middleware (afaik) are exporting entire subapps.

This just needs to move the 501 check into the `this.server` handler & it should be good to go. Gunna have time for it tonight~
