### ISSUE TITLE
[Feature suggestion] Write plugin for serverless framework

### ISSUE THREAD

**Issue by GitGangGuy** [lukeed/polka#106]
I guess you guys have A LOT of work and I'm just adding another suggestion to the pile, but I'd really like to emphasize how many people power their websites with serverless architecture. Still, many people just need a server for ssr etc. which is why they build complicated architecture, often supported by a framework like the [serverless framework](http://serverless.com) (Probably one of the more popular ones). The problem: Express seems to be the standard in the serverless industry since most plugins only support turning express apps into lambda functions and hook 'em up with the rest of the architecture. In my case, I'm using [serverless-http](https://github.com/dougmoscrop/serverless-http) which doesn't support polka currently. I'll be opening an issue/feature request there too, but maybe you guys could see if you could push your highly performant server solution into the serverless industry. I believe this would allow us all to profit from a performance increase and cost decrease for serving our serverless functions.

**Comment by devcat** [comment]
Most serverless deployments are per endpoint or job type so routing just becomes overhead when you use either express or polka

You would barely notice any numbers increase as most optimizations are targeted at constantly running http server not serverless platform where instances get killed after no use

If you really need extremely fast serverless javascript based on time to answer request you can look into cloudflare workers


In your case you need ssr which cloudflare workers can do perfectly and with extremely great response time

**Comment by GitGangGuy** [comment]
Okay, thanks 😅 I'm using [serverless-http](https://github.com/dougmoscrop/serverless-http) for the serverless framework at the moment to deploy my ssr app to AWS, but I'm looking into Cloudflare Workers just now. Always thought about merging over to them. Serverless-http is going to introduce experimental support for polka in 2.2.0, until then I'll be using fastify (or switch to cloudflare). Thanks a lot!

**Comment by lukeed** [comment]
It looks like as of yesterday, `serverless-http` supports Polka 👍 If you helped instigate that, thanks~!

Worth mentioning, even though it's early & unreleased, the Polka 1.0 suite of packages will include "adapters" for AWS Lambda, GCP Functions, and Cloudflare Workers. I'm currently using/working on the Worker adapter as it has me the most excited.
