### ISSUE TITLE
Thanks to Polka

### ISSUE THREAD

**Issue by kethan** [lukeed/polka#108]
Hi All,

I have created a universal router based on Trouter and Polka. Kindly check and let me know your feedback.

urout - https://www.npmjs.com/package/urout - Universal Router.
userve - https://www.npmjs.com/package/userve - Express like router framework.
ubrow - https://www.npmjs.com/package/ubrow - Express like browser router.

Thanks

**Comment by lukeed** [comment]
Very cool! 😄 Glad to give some inspiration 👏 

Just so you know (you probably do!), Trouter _can_ actually be run in the browser as is – you just have to attach event listener(s) to do the matching. And then a more browser-based solution is [`navaid`](https://github.com/lukeed/navaid).

Congratulations to you, good suite of libs 🎉
