### ISSUE TITLE
Question: handle http.createServer error

### ISSUE THREAD

**Issue by RomiC** [lukeed/polka#112]
I've just started using polka as a server and have a question about error-handling. I would like to handle errors occurred while creating `http.Server`-instance I.e. `listen EADDRINUSE: address already in use`. To do so, I have to create my own instance of server and pass it as `server`-option to `polka()`-function:
```js
const http = require('http');
const polka = require('polka');

function errorHandler(err) {
  // handle error somehow...
}

const serverInstance = http.createServer().on('error', errorHandler);
const server = polka({server: serverInstance, onError: errorHandler});

server.listen(3000);
```
Is it the only way how I can handle such kind of errors? Are there any ways just to pass such a handler as a parameter to `polka()`-function?

**Comment by lukeed** [comment]
Hey, couple of ways:

1) Use `polka` only, and then attach your `error` listener to the underlying server that Polka creates for you:

    ```js
    const app = polka();
    app.server.on('error', errorHandler);
    app.listen();
    ```

2) The better way (IMO) is to check for the PORT being in use before you even attempt to start up.
That could be done with [`port-authority`](https://github.com/Rich-Harris/port-authority) or [`get-port`](https://github.com/sindresorhus/get-port). The idea is that you tell _it_ what port you plan on using and it'll either raise an error ahead of time OR give you an alternative port to use. 

    It's not Polka, but here's an example using `get-port` within my `sirv-cli`: https://github.com/lukeed/sirv/blob/master/packages/sirv-cli/boot.js#L61

Hope that helps!
