### ISSUE TITLE
How to get full request URL?

### ISSUE THREAD

**Issue by pke** [lukeed/polka#114]
Is it possible to get the requests origin somehow to compose new URLs in responses based on it?

**Comment by lukeed** [comment]
Polka is a light wrapper around Node.js server and its Request/Responses classes.

Within the request, Polka deals with URL pathing and query segments. The `req.originalUrl` is always the full URL and never changes for the request's lifecycle. The `req.url` is the complete URL relative to the processing application. The rest you can find listed in the docs

If you're interested in the origin of the request, you can look at `req.headers.origin` or `req.headers.referer` which is native Node bits

Hope that helps!
