### ISSUE TITLE
Get all the base paths of `use` apps

### ISSUE THREAD

**Issue by pke** [lukeed/polka#117]
```js
polka()
.use("counter", createStateApp(require("./fsm/counter.js")))
.use("search", createStateApp(require("./fsm/searchMachine.js")))
```

Is it possible to register a root path that has access to all the sub-apps?

like?

```js
const app = polka()
.use("counter", createStateApp(require("./fsm/counter.js")))
.use("search", createStateApp(require("./fsm/searchMachine.js")))
.get("/", (req, res) => {
  Object.keys(app.apps).map(...)
})
```

**Comment by lukeed** [comment]
Yes, what you posted should be fine though not really recommended.

Also, the discord channel is a more appropriate place for general questions/support.

**Comment by pke** [comment]
Thanks, why wouldn't it be recommended? Cause its not documented I guess?

I was looking for means to ask general questions but the discord channel escaped me. It doesn't seem to be mentioned in the readme? Where can I find it?

**Comment by lukeed** [comment]
Ah, sorry, it's here: https://discord.gg/xrRvfYV

Not recommend because you're relying on Polka internals to do something. It's not documented as public API because it's not meant to be used. For example, `this.apps` is removed in upcoming 1.0

**Comment by pke** [comment]
Thanks for the link to the discord group.

Too bad I can't use `apps` anymore. I have to come up with another pattern then.
As you might have already guessed I am looking for a faster alternative to `koa` but are still in the mindset of it. I looked at `fastely` but with its mixture of error handlers, middleware, plugins it seemed to have a too big of an API for my taste.

**Comment by lukeed** [comment]
No problem :) What is it youre actually trying to do?

**Comment by pke** [comment]
I want to mount n-subapps to different root paths. Then I want have a main apps root path to respond with all the available subapps root paths. So I guess I can just keep that relation outside of polka in the first place:

```js
const apps = {
  "counter": createCounterApp,
  "search": createSearchApp,
}
Object.keys(apps).forEach(key => polka.use(key, apps(key)())
```
