### ISSUE TITLE
async and non-async middleware don't mix

### ISSUE THREAD

**Issue by pke** [lukeed/polka#118]
Given this setup:

```js
const sirenResponse = (req, res, next) => {
  try {
    next()
    if (!res.finished) {
      send(res, res.statusCode || 200, data)
    }
  } catch (e) {
    res.statusCode = 500
    data = e.message
  }
}

async function errorPage(req, res, next) {
  try {
    await next()
  } catch (err) {
    const Youch = require("youch")
    const youch = new Youch(err, req)
    const body = await youch.toJSON()
    send(res, 500, body, {
      "Content-Type": "application/json"
    })
  }
}

const app = polka()
  .use(sirenResponse)
  .use(errorPage)
  .get("/error", () => { throw new Error("Ooops") })
```

The `sirenResponse` will send its output before the `errorPage` await for `youch.toJSON` is finished.

This kind of setup works in koa. If I make both handlers async and `await next()` in the `sirenResponse` middleware it works as expected.

**Comment by lukeed** [comment]
What is "expected" in that case?

This is just a complete misuse of `next` as it's supposed to signify "I'm done with this function". I imagine a lot of koa patterns won't work here because we're not trying to emulate koa at all.

**Comment by pke** [comment]
Ah ok, sorry that was a misunderstanding on my side. Coming from `redux` and `koa` the middlewares there really live and act in the middle of the chain. That is, they can act upwards and/or downwards the chain of middlwares. So something like that:

```js
async function requestTime(req, res, next) {
  const time = Date.now()
  await next()
  res.set("Response-Time", Date.now() - time)
}
```

would work in both `redux` and `koa`.

What I wanted to achieve is a global error handler, that generates a error json that is then handed down to a `accept` aware serialiser that finally composes the body of the response.

**Comment by lukeed** [comment]
Cool. Yeah I'd probably recommend `polka@next` for you. It's very stable and already in production in multiple places... It's the supporting ecosystem that is still under development.

With that, the try/catch behavior you needed (#12) is handled uniformly by `opts.onError` handler, in which you can define that all-encompassing behavior

**Comment by pke** [comment]
any updated docs what will be new in @next yet?
