### ISSUE TITLE
Malformed URI crashes polka

### ISSUE THREAD

**Issue by dekdevy** [lukeed/polka#119]
Version: ^1.0.0-next.7

```
const polka = require('polka')
const app = polka()
app.listen(1234)
```

Then do a GET to `http://localhost:1234/%2`

Polka crashes:
```
url = req.url = obj.href = obj.path = obj.pathname = obj._raw = decodeURIComponent(url);                                                                                              ^
URIError: URI malformed
    at decodeURIComponent
```

How do I catch or fix this? 0.54 does not crash, btw. It ends with 400.

**Comment by lukeed** [comment]
Thanks! Fixed and now releasing

**Comment by dekdevy** [comment]
Thanks for the quick fix. I noticed sirv uses this file too and therefore is also subject to the same error, btw.

**Comment by lukeed** [comment]
Thanks, fixed in `sriv@next` since its latest isn't using the `polka/url@next` 👍
