### ISSUE TITLE
Data Detections in send-type are very minimal

### ISSUE THREAD

**Issue by peternann** [lukeed/polka#122]
... But the documentation really doesn't indicate that.

Detecting XML from the first 5 chars "<?xml" was expected for me.

**Comment by lukeed** [comment]
I mean, I think it's pretty clear about what it does detect: https://github.com/lukeed/polka/tree/master/packages/send-type#data-detections

It just covers the basic types. You can always set your own content-type through `res.setHeader` or thru send-type argument.

Hope that helps!

**Comment by peternann** [comment]
Yeah, that looks pretty clear. I think I missed that somehow. Thanks.
