### ISSUE TITLE
is this ok?

### ISSUE THREAD

**Issue by neuronetio** [lukeed/polka#126]
https://github.com/neuronetio/polonez

**Comment by neuronetio** [comment]
sorry for not forking it the right way, I didn't know how to fork, it was the easiest way to make new repo, but I would also be pissed off when someone stole my work
so again sorry

If those fork is ok you can close the issue

**Comment by lukeed** [comment]
Yes, thank you.

You see how it's now an actual fork w/ the complete, original git history and contributor list?

<img width="227" alt="Screen Shot 2020-01-28 at 7 22 33 PM" src="https://user-images.githubusercontent.com/5855893/73325542-c07d6580-4203-11ea-8f67-2d2dbc78d103.png">

<img width="1018" alt="Screen Shot 2020-01-28 at 7 22 39 PM" src="https://user-images.githubusercontent.com/5855893/73325545-c3785600-4203-11ea-9f5e-6418a8bd2d6a.png">

That's a fork – and those are totally fine. I have no problem with forks, so long as they respect their source. This means that licenses cannot be tampered with and anywhere the authors' names appeared must be left intact.

So, the only remaining item is `rrrouter's` `package.json` file. We can be listed as co-authors there, or you can move me to a `contributors` list – it doesn't really matter to me which you choose.

**Comment by neuronetio** [comment]
Yap, I understand now, my fault, sorry again

**Comment by lukeed** [comment]
No problem, thanks for your understanding and cooperation 👍
