### ISSUE TITLE
Decouple global middleware from '/' path

### ISSUE THREAD

**Issue by andrhua** [lukeed/polka#128]
Currently `/` path considered to be equivalent to global, e.g. following middleware will be applied to all existing routes. However this comes with a limitation that I cannot specify middleware for root exclusively. 
For example, if my application has a login form on root page, which is not rare at all, I cannot ensure that this page is visited only by unauthorized users, and hence, Polka forces me to move this functionality to more specific route. 
Also in my humble opinion, this whole thing doesn't make any sense with 

> If a base pathname is provided, all functions within the same use() block will only execute when the req.path matches the base path.

**Comment by lukeed** [comment]
Hey there,

You can:

```js
// you spoke about this
app.post('/', route_middleware, login_handler);

function root_only(fn) {
  return async function (req, res, next) {
    if (req.path === '/') return fn(req, res, next);
    next();
  }
}

app.use(root_only(foobar), other_handlers);
```

This pattern came from Express and is therefore generally common.

> Also in my humble opinion, this whole thing doesn't make any sense with

This documentation is just saying that:

```js
app.use('/items', foo, bar);
```

...will only execute `foo` and `bar` if the incoming request begins with `/items/...`. Not sure what issue you're finding with this. Is it the wording?

**Comment by andrhua** [comment]
Thanks for quick reply and solution. 

> Is it the wording?
I meant that there it says that it will execute on exact match, and in Middleware section all of a sudden, `/` matches everything, despite fact that `/` === `/` and `/` only.

Still I think this is a thing where Polka can be smarter then Express or that would break too many existing middleware strategies?

**Comment by lukeed** [comment]
Ah – then it's the wording.

It's a prefix match, as is Express. You can only opt for _exact_ matches if you drop into single-verb routes ... otherwise any `use()` declaration is a group-type assignment.

That is... unless you use `polka@next` 

There we've added support for RegExp-based route patterns (via [Trouter](https://github.com/lukeed/trouter#pattern)), which means that you could be explicit with any route (use() or method-based) and do an exact match pattern:

```js
app.use(/^\//$/, root_only_any_method);
app.use(/^[/]movies[/](?<title>\w+)[/]?$/, (req, res, next) => {
  // req.params.title = 'value';
  next();
})
```

> Can see other test cases here: https://github.com/lukeed/trouter/blob/master/test/index.js#L493-L560

**Comment by andrhua** [comment]
Nothing works fast enough unless you write it yourself? :wink: Thanks again, I guess gonna go with plain path check inside middleware.
