### ISSUE TITLE
view templating like pug

### ISSUE THREAD

**Issue by riiccardo** [lukeed/polka#129]
``` javascript

const express = require('express');
const app = express();

const instructors = ['Elie', 'Tim', 'Matt'];

app.set('view engine', 'pug');

app.get('/', function(req, res) {
  return res.render('index', { instructors });
});

app.listen(3000, function() {
  console.log('Server is listening on port 3000');
});
```

hey @lukeed 

can u show us how to transform `express` app above to `polka` and using pug in templating 

and `server side rendering` pug 

thanks 😍🤗

**Comment by lukeed** [comment]
Hey there!

Can you view my comment here (https://github.com/lukeed/polka/issues/73#issuecomment-428315454) and see if that answers your question? It would apply to any templating system.

There's no other equivalent for Polka (stable), intentionally. I still haven't decided if I'll add view-engine support for the 1.0

**Comment by riiccardo** [comment]
thanks for quick answer

it would be nice if template engine supported

**Comment by lukeed** [comment]
I'm undecided. There may be a package that makes it easy to setup (basically doing the above) but otherwise it's one of the worst parts about Express imo - separate domain concern.

Will close this since it's already on the agenda and is a duplicate. Thanks!
