### ISSUE TITLE
Update trouter to latest version

### ISSUE THREAD

**Issue by T1MOXA** [lukeed/polka#139]
https://github.com/lukeed/trouter/commit/ca4c61d11f538218680b11982211af427f794d32

**Comment by lukeed** [comment]
Hey,

This is already the case with `polka@next`: https://github.com/lukeed/polka/blob/next/packages/polka/package.json#L22

It can't be done to `polka@0.5.x` because it's a breaking change. The 3.x is the foundation of `polka@next`

Thank you though

**Comment by T1MOXA** [comment]
Thanks for the answer

**Comment by lukeed** [comment]
Of course
