### ISSUE TITLE
@polka/redirect source code

### ISSUE THREAD

**Issue by manuel3108** [lukeed/polka#153]
Just wondering where the source code of `@polka/redirect` / https://www.npmjs.com/package/@polka/redirect is located. I would expect it to be in this repository as the repository of the site links here. Furthermore from repo structure I would expect it to be in `/packages`.

Am I missing something?

**Comment by lukeed** [comment]
Hey, you have to look in the `next` branch since `@polka/redirect` is still under the `next` npm tag

https://github.com/lukeed/polka/tree/next/packages/redirect

**Comment by manuel3108** [comment]
Ahh I see :D
