### ISSUE TITLE
@polka/parse: wildcards are unsupported

### ISSUE THREAD

**Issue by rschristian** [lukeed/polka#156]
Hello,

I'm not sure whether this is something in the scope or another part of the Express-specific behaviors, but I ran across an issue replacing Express's `raw()` with Polka's.

A server I'm converting to use Polka was using `express.raw({ type: '*/*' })`. However, I can't swap that out for Polka's `raw()` as wildcards don't seem to be handled currently: https://github.com/lukeed/polka/blob/3b4d86630f96083a041634421d11d8b2818a8b34/packages/parse/index.js#L18

As the `type` that I have passed to the raw parser is never going to mach up with the `Content-Type` header, no parsing will ever be done.

**Comment by lukeed** [comment]
Hey, no wildcard but you can use an empty string to accept everything. You can also provide any value so long as it's included -- you can use this to match groups for example (eg `image/`)

**Comment by rschristian** [comment]
Oh, looks like I then guessed at the wrong issue. Odd.

I did a one-off test where I set the `type` to `application/json` and it worked without a hitch, so I assumed that was the problem. I do need to accept all content types however, so this isn't a long-term solution. 

Strangely I get an empty object instead of a parsed value when using an empty string / any other value. Will need to look into that further.

**Comment by lukeed** [comment]
Sorry, I meant to say that my suggestion was tied to the `parse` export, since there's no default there. Its exported so that you can roll your own anything. All named exports are named commons (and align with `body-parser` defaults iirc)

```js
import { parse } from '@polka/parse';

polka()
  .use(
    parse({ 
      type: '',
      encoding: null // to match raw
    })
  )
```

If you just want to use `raw`, you can pass `type: '/'` so that it doesn't fall through 😉

**Comment by rschristian** [comment]
Ah, apologies. Should've realized that's what you meant. 

Good point about `type: '/'` too, didn't dawn on me 😅

All's working great, so I'll close this out. Thank you!
