### ISSUE TITLE
`@polka/url` `1.0.0-next.15` broke semver

### ISSUE THREAD

**Issue by andylizi** [lukeed/polka#166]
For example, a fresh install of older versions of `sirv` will:
```
TypeError: parser is not a function
    at .\node_modules\sirv\build.js:163:30
```

**Comment by lukeed** [comment]
In `@next` variants you can make breaking changes between any `@next` version. Same is true for any other prerelease tag (rc, beta, alpha, etc). There have been other breaking changes in the polka `@next` lifecycle -- that's what it's here for.

Sirv was updated immediately to reflect this change. If you want to use old software, you can, but it's your responsibility to pin/lock your dependency tree. This is why all package managers have a lockfile. You can also use something like `resolutions` (I know yarn & pnpm support this) to override a package resolution during install -- if not going with the lockfile route.

Hope that helps
