### ISSUE TITLE
Switch to `undici` instead of `http`

### ISSUE THREAD

**Issue by kurtextrem** [lukeed/polka#170]
As Polka is performance oriented, maybe check out this new lib by the nodejs team: https://github.com/nodejs/undici
It's faster than http, see: https://undici.nodejs.org/#/?id=benchmarks

**Comment by TrySound** [comment]
Looks like it's only client and does not provide an ability to create server.

**Comment by lukeed** [comment]
Correct. Undici is a http client

**Comment by kurtextrem** [comment]
Oh damn - overseen that, sorry.
