### ISSUE TITLE
TypeError: http.createServer is not a function

### ISSUE THREAD

**Issue by c4kaci** [lukeed/polka#171]
Hi,

I would like to use `polka` with `http-proxy-middleware`
My code:
```
const { createProxyMiddleware } = require('http-proxy-middleware');
const polka = require('polka');
```

```
        const app = polka();
	try {
		app.use(
			createProxyMiddleware({
				target: 'http://jsonplaceholder.typicode.com',
				changeOrigin: true, // for vhosted sites, changes host header to match to target's host
				secure: false,
				logLevel: 'debug',
			})
		);
	} catch (err) {
		console.log("App use: " + err);
	}

	try {
		app.listen(3000);    <----------------- Here 
	} catch (err) {
		console.log("Listen: " + err);
	}
```
The "app.use" unit works well.  (it does not go into the catch)

The "app.listen(3000);" throw the error `TypeError: http.createServer is not a function`

Exist some official fix for that?
How can I fix it?   Workaround?

thx
kaci

**Comment by lukeed** [comment]
Hey, you probably need to install [`@types/node`](https://www.npmjs.com/package/@types/node). It is a native, built-in function – your TS just isn't made aware of it yet.

**Comment by c4kaci** [comment]
Thank you @lokeed for your quick answer but unfortunately it did not solve the problem.

**Comment by c4kaci** [comment]
@lukeed 
Maybe causes the problem that this is a frontend application? 
I'm newbie in node development. 

Problem is this is an Adobe Photoshop plugin. 
Photoshop use embedded node.js and embedded chrome browser.
I would like to connect to our java app server but I need to ride the cors and fake SSL problems.
Therefore should I use an embedded proxy in my plugin.

**Comment by lukeed** [comment]
Polka is a Node.js framework. You need to be running in a Node environment for it to work.

Closing, but please let me know if I misunderstood. Thanks~!
