### ISSUE TITLE
types - `polka.use` not compatible with `express.RequestHandler`

### ISSUE THREAD

**Issue by benmccann** [lukeed/polka#173]
`polka().use(compression({ threshold: 0 })` gives me a red squiggly in VS Code. You can see it by opening up SvelteKit's `packages/adapter-node/src/server.js` in VS Code. `compression` returns a `express.RequestHandler`.

**Comment by lukeed** [comment]
The types will never line up. That's okay. Use `as Middleware` or ts-ignore it.

They're different libraries with different amount of signatures and type hints.

**Comment by benmccann** [comment]
The types lined up with the types from DefinitelyTyped on an older version of Polka, so I thought it should be possible
