### ISSUE TITLE
Typescript middleware editor errors

### ISSUE THREAD

**Issue by Eyewavu** [lukeed/polka#189]
So i got a following error in vscode on line `.use(logger)` 
`Argument of type '(req: Request, res: Response, next: Next) => void' is not assignable to parameter of type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.`

i used "@types/polka" package for typings

Here's the code i wrote:
```ts
import polka, { type Next } from "polka";

function logger(req:Request, res:Response, next:Next) {
  console.log(`~> Received ${req.method} on ${req.url}`);
  next(); // move on
}

polka()
  .use(logger)
  .get("/users/:id",(req,res) => {
    
    res.end(`Hi user ${req.params.id}`)
  })
  .listen(3000)
```

To be clear, this code works without any problems, it's just compiler errors i'd like to eliminate in my editor

**Comment by lukeed** [comment]
You didn’t import Request and Response, so that means you’re pulling in the global types which correspond to Web APIs. This type error is correct since a web Request/Response isn’t compatible with the ones that the rest of types/polka is expecting
