### ISSUE TITLE
Remove Promise around Listen

### ISSUE THREAD

**Issue by lukeed** [lukeed/polka#19]
This seemed like a good initially just because of `then/catch`, but there are a few problems with this:

1. Calling `.listen()` does not return the Polka instance directly, so it forces `listen` to always be called last.

2. It also prevents one-line initializers for a server.

    ```js
    const server = polka().listen(3000);
    //=> server is Promise, not Polka instance
    ```

3. The top-level `then` and `catch` blocks make it seem like `catch` is the global catch-all handler.

Instead, `.listen()` would expose the underlying `server.listen` method directly, meaning that signature is the same as all other servers.

```js
polka().listen(PORT, err => {
  if (err) throw err; // or whatever you want to do
  console.log(`> Ready on localhost:${PORT}`);
});
```

This would also remove 5 lines of code 😆

**Comment by Youngestdev** [comment]
I think the new development is cool !

**Comment by lukeed** [comment]
Sorry @Youngestdev, which do you mean?

**Comment by Youngestdev** [comment]
```js
polka().listen(PORT, err => {
  if (err) throw err; // or whatever you want to do
  console.log(`> Ready on localhost:${PORT}`);
});
```
That looks cool

**Comment by lukeed** [comment]
Got it, thanks!

**Comment by lukeed** [comment]
Thanks @yamalight~! I'm still slightly in favor of removing the Promise version because I'm seeing a lot of early users trying to `server = polka().listen(PORT)`... especially for tests. The "drawback" is needing to separate this into two lines, which isn't the end of the world but it slightly annoying since no one's used to it. 🤔

**Comment by yamalight** [comment]
@lukeed how about allowing to do `server = await polka().listen(PORT)`?

**Comment by lukeed** [comment]
That's far more complicated and would use`Promise` on the main application, affecting performance.

**Comment by yamalight** [comment]
fair point 😃

**Comment by terkelg** [comment]
I think we should remove the promise. I actually had some problems with. It took me a while to realise that `.listen()` not returns an `http.Server` object.

This is also another step towards better express compatibility like #29 ... and less code! What's not to like.

**Comment by mram** [comment]
Changing to something like
``` js
listen(...args) {
  (this.server = this.server || http.createServer()).on('request', this.handler);
  this.server.listen(...args);
  return this.server;
}
```
would be closer to honouring options for [net.Server](https://nodejs.org/api/net.html#net_server_listen)

**Comment by lukeed** [comment]
Yup! That's actually exactly the code I was going to write. I just (still) haven't decided if this should happen or not. Pros & cons for each side.

**Comment by mram** [comment]
Yeah. And I think promisification can be done by
``` js
// sketchy, untested code ahead

const {promisify} = require('util');
const app = require('polka')();

app.use((req, res) => {
  res.end(200, 'OK');
});

const start = promisify(app.server.listen);  // assuming server already exists

start()
  .then(...)
  .catch(err => ...);
```
(😜)

**Comment by peappeap** [comment]
now i was start node index.js and i get ---- attempt to reconnect has failed--- in browser how can i do sir ?
