### ISSUE TITLE
Module not found: Error: Can't resolve 'http' in '/home/marc/pcloud/SiteWeb/LeibnizProject/node_modules/polka'

### ISSUE THREAD

**Issue by mcoulont** [lukeed/polka#190]
Polka uses the http package (in index.js) but this package seems to have been removed because it contained malicious code : see [this page](https://www.npmjs.com/package/http).

What am I supposed to do to use Polka?

**Comment by lukeed** [comment]
http is a native Node module. Sounds like your build setup is missing a “prefer natives” config/plugin which helps prevent these same-name-packages from being involved.

**Comment by lukeed** [comment]
Polka is a node http framework. Won’t work in the browser
