### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by lukeed** [lukeed/polka#2]
Should definitely include a directory of examples since a lot of people prefer to learn by doing. 🙋‍♂️ 

_Also is a nice way to ensure/validate that these things are possible._

- [x] Async
- [x] HTTPS
- [x] JSON API
- [x] Static Assets
- [x] Sub-applications
- [x] Body parser
- [ ] Others?

**Comment by yamalight** [comment]
@lukeed I've created a simple static assets example here: https://github.com/lukeed/polka/pull/7
There's also a small change to a core, would be great if you could have a look. 
And thanks for the awesome framework!

**Comment by lukeed** [comment]
Think we have a fair amount of examples now~
