### ISSUE TITLE
Expose Polk().close function

### ISSUE THREAD

**Issue by ansarizafar** [lukeed/polka#27]
Native http has a close() function  https://nodejs.org/api/http.html#http_server_close_callback which stops the server from accepting new connections. This is necessary for graceful shutdown of node server.

**Comment by lukeed** [comment]
You have access to the underlying native server.

```js
const app = polka();

// start it at some point
app.listen(PORT);
//~> this is calling 'app.server.listen' under the hood

// shut it down manually
app.server.close();
```
