### ISSUE TITLE
Adding Polka to fastify benchmarks

### ISSUE THREAD

**Issue by trivikr** [lukeed/polka#3]
It's interesting to see we're getting more options for HTTP servers.
Competition is good for the community.

Fastify has [benchmarking mechanism](https://github.com/fastify/fastify#benchmarks) for different NodeJS servers.
Is there a plan of adding Polka benchmarks to the table?

**Comment by lukeed** [comment]
Closing this in favor of https://github.com/fastify/benchmarks/issues/43

Thanks!
