### ISSUE TITLE
Can I use Graphql in polka?

### ISSUE THREAD

**Issue by lagmanzaza** [lukeed/polka#32]

**Comment by ThiccCat** [comment]
With usage of external module like (graphql-js)[https://github.com/graphql/graphql-js] yes

**Comment by lagmanzaza** [comment]
Thank you sir

**Comment by lukeed** [comment]
Hey, I don't actually use GraphQL but I added a quick little demo to show how you might approach.

There's likely better ways & better tools out there -- but it all comes down to how much abstraction you want / are comfortable with.

Hope it helps!

**Comment by lagmanzaza** [comment]
Wow Thank you sir
