### ISSUE TITLE
Parameters in sub-apps

### ISSUE THREAD

**Issue by cwhitby** [lukeed/polka#35]
Am I correct in assuming that using route parameters as part of the base in `use` are not supported?

It would be great if I could do the following, for example:
``` javascript
const polka = require('polka')

const clientHandler = require('./clientHandler')
const contactSubApp = require('./contactSubApp')

polka()
  .get('/:clientid', clientHandler)
  .use('/:clientid/contacts', contactSubApp)
```

**Comment by lukeed** [comment]
No, sorry, this isn't possible and AFAIK it isn't with Express either.

The `mergeParams` with Express is the closest thing I can think of, but can still be problematic and isn't generally recommended last I remember.

If your apps are anything like mine, you probably only have a `GET` and a `POST` on the `/:client/contacts`. I would define those manually -- or you can do some parsing from within `contacts` based on the `req.originalUrl`.

**Comment by cwhitby** [comment]
Didn't think so.

I've used `mergeParams` in Express before and you're right, it worked but never perfectly.

Manual it is. Thanks!
