### ISSUE TITLE
Comparison with Japronto?

### ISSUE THREAD

**Issue by deadcoder0904** [lukeed/polka#40]
Hey Luke, first of all awesome project.

Its not an issue but a comparison with a complete different framework of a different language. Since I want to cut down server cost & all & provide an API server for a SAAS but I work with Node JS & have only little experience with Python. 

So I was looking at the project [Japronto](https://github.com/squeaky-pl/japronto) its freakishly fast. More info about it [here](https://medium.freecodecamp.org/million-requests-per-second-with-python-95c137af319). I've checked the benchmarks & I don't understand which ones to compare between Japronto & Polka. 

Polka benchmarks says `41053.98` & then `414739 requests in 10.10s`, which ones to compare ❓

Can Polka be as fast as Japronto like it says it gives 1 million requests/second❓

**Comment by deadcoder0904** [comment]
Thanks @lukeed, didn't knew about that link

**Comment by lukeed** [comment]
You bet! Was in your shoes too, before deciding to build Polka lol

**Comment by paulocoghi** [comment]
Curiously, Polka is faster than Japronto (almost twice as fast), according to [which_is_the_fastest](https://github.com/tbrand/which_is_the_fastest/blob/master/README.md).

**Comment by paulocoghi** [comment]
Another point is that Polka will shine even more if it is possible to use it in **[cluster](https://nodejs.org/api/cluster.html)** mode, since the node part of the benchmark is running in a single thread.

**Comment by lukeed** [comment]
I heavily suspect that's a bug with the new benchmark suite 😆That repo has undergone a bunch of changes in the last week or so, and Japronto got caught in the mix.

But yes, +1 re:cluster mode. On my machine (and Node 8.9), Polka goes from 42k req/s to ~95k req/s with simple benchmarks.

**Comment by waghanza** [comment]
@lukeed @paulocoghi the benchmark suite above is actually unrevelant (I know it, I maintain it). Soon, results will be more accurate, I'm working on it => https://github.com/the-benchmarker/web-frameworks/pull/632 :heart:

**Comment by waghanza** [comment]
And `node` are running with`pm2` => not on a single thread then

It's the only way I've found to make`node` implementations uniform 😁

Any ideas are welcome :heart :
