### ISSUE TITLE
Polka.all() handler

### ISSUE THREAD

**Issue by mram** [lukeed/polka#45]
Implement a `app.all()` handler similar to the [express'](https://expressjs.com/en/4x/api.html#app.all) that looks like
``` js
app.all(path, callback [, callback, ...]);
```
and
* if path is `*` then run the callbacks as global middlewares
* if path matches a base then run the callbacks as global middlewares (with base stripped) before calling the base handler

I think this might be of low priority and may degrade performance but might be helpful.

**Comment by ianwalter** [comment]
@mram So the benefit of adding this would be that you could handle more complex routes (e.g. `/hello/:id`) than you could by using middleware (`.use`) right? I wonder if it would be worthwhile to just handle middleware routes like handler routes.

**Comment by mram** [comment]
Actually polka currently uses trouter to handle the methods like GET, POST, DELETE etc, the middlewares are called irrespective of any http method, so I am actually trying to propose a way where the middlewares for specific routes can be specified (so the `all`, `path` is the route). For these middlewares the base will be stripped.

This is quite confusing, even to me, but I think this might be useful if everyone feels so.

The only reason for this is that trouter can find a handler based on the http method only. This `.all` "might" provide a way to that.

**Comment by lukeed** [comment]
I personally find this method functionally useless in Express, but I know others have found ways to need it in their applications lol.

As pointed out, this change has to be made in Trouter (see https://github.com/lukeed/trouter/issues/1) instead of Polka. The change is stashed locally somewhere and will be part of the next release.

Thanks guys!
