### ISSUE TITLE
Problem with passport-local 

### ISSUE THREAD

**Issue by antonheryanto** [lukeed/polka#49]
Thanks for nice project, have benchmark it and performance better compare to express

but stumble with passport-local which require res.redirect method which not available in polka
any workaround how to add res.redirect ? 
still working but if auth problem will cause crash

**Comment by lukeed** [comment]
Sure!

You can add your own global middleware (before passport) that mutates `res` with a redirect method. I haven't added the full Express helpers yet, sorry.

```js
polka()
  .use((req, res, next) => {
    res.redirect = //...
    next()
  })
  // ...
```

**Comment by antonheryanto** [comment]
Thank you very much, no problem. this already tremendous project already

**Comment by lukeed** [comment]
Thanks!

**Comment by kylecordes** [comment]
I've run into the same issue; and will no doubt be able to work around the same way.

But, I think this really should have been a feature request: that Polka pickup some more of the commonly supported methods like redirect, so that it "just works" with more of the ecosystem out of the box. That's a good idea, right?]

**Comment by lukeed** [comment]
Yeah, Polka will 99% likely have variadic route handlers (#18). I have a WIP branch of it locally, but still need to optimize it & test it thoroughly before releasing as it changes the internal logic quite a bit.

Redirect won't be included ootb &mdash; at best it'll be a supplemental package you "mount" via `use()`, or it'll be its own helper just like `@polka/send`. Attaching a redirect method affects/mutates _every_ cycle, so better be damn sure you actually want that work being done.

**Comment by mhaagens** [comment]
Any chance of an example of a redirect from within a request handler?
I need to possibly do redirects after rendering a react app server side within a request.
And thanks for this project, works awesome so far!
