### ISSUE TITLE
[Question] Any plan to open a Github org named Polka

### ISSUE THREAD

**Issue by motss** [lukeed/polka#51]
First of all, Polka is an awesome take for being one of the fastest web servers written in Node.js.

Just curious to know if any plan to move everything to a Github org named `Polka` and scoped everything in `@polka/<package_name>`, but `polka` itself can choose not to be a scoped package as I noticed most of the packages are `@polka` scoped.

**Comment by lukeed** [comment]
Thanks! No, I don't really see any benefit to that -- it crossed my mind in the early days too. It's just me (so far) and everything scoped is/would be an official package, which belongs in the (this) monorepo anyway.

Basically there's no point in making the move

**Comment by motss** [comment]
Fair enough. Thanks for the answer.
