### ISSUE TITLE
socket-io example not working

### ISSUE THREAD

**Issue by motss** [lukeed/polka#53]
https://github.com/lukeed/polka/blob/734ee317866da071b3112991c751ba3b42dc9c81/examples/with-socketio/index.js#L9

_**stderr**_

```sh
server.listen(PORT, _ => {
       ^

TypeError: Cannot read property 'listen' of undefined
```

**Comment by lukeed** [comment]
Oh yeah, I need to fix this. It no longer works as if 0.4 because `server` is not undefined until `listen()` is called, unless one is provided.

**Comment by lukeed** [comment]
Fixed in https://github.com/lukeed/polka/commit/a9f0f583d848f1169d07bc89e5c630db6a76452e 👍
