### ISSUE TITLE
Can support serve static files

### ISSUE THREAD

**Issue by muhammadridho** [lukeed/polka#58]
Hi, can this support to serve static files ?

**Comment by lukeed** [comment]
Hey, yes there are some examples: [`with-sirv`](https://github.com/lukeed/polka/tree/master/examples/with-sirv) and [`with-serve-static`](https://github.com/lukeed/polka/tree/master/examples/with-serve-static).

Some of the others have static file integrations too but aren't the main purpose of those particular demos.

Hope that helps!
