### ISSUE TITLE
named parameters and req.query

### ISSUE THREAD

**Issue by ryanramage** [lukeed/polka#6]
I have a route defined with

    app.put('/hash/:id', (req, res) => {

and when a do a PUT with a querystring as well as a named param, eg

    http PUT "localhost:12227/hash/ab?ts=123132&ryan=3232"

the query is appended to the named param, eg

     console.log(req.params.id, req.query)
    > ab?ts=123132&ryan=3232 ts=123132&ryan=3232

**Comment by Youngestdev** [comment]
Sorry, can you break down what you're trying to say ?

**Comment by ryanramage** [comment]
req.params.id should be just 'ab' in this case, but it is 'ab?ts=123132&ryan=3232'.

the querystring is being appended to the named param when it should not be.

Maybe this is just a bug in https://github.com/lukeed/trouter but I thought I would raise it here first.

**Comment by lukeed** [comment]
Ah, whoops! Never ran into this because none of my apps rely on query params.

Easy fix, out shortly.

**Comment by lukeed** [comment]
Released in `0.2.1`, thanks!

**Comment by ryanramage** [comment]
Thank you!
