### ISSUE TITLE
how to parse body data?

### ISSUE THREAD

**Issue by itaditya** [lukeed/polka#60]
Hi, in express we use body-parser and then extract body data via `req.body`. How can we do that in polka?

**Comment by lukeed** [comment]
Hey, same thing!

Example: https://github.com/lukeed/polka/blob/master/examples/with-body-parser/index.js#L2-L6

**Comment by itaditya** [comment]
Oh thanks, sorry for troubling you. I should have looked deeper in the repo.

**Comment by lukeed** [comment]
Not a problem! There's quite a few examples there. If you think one is missing / should be added, lemme know
