### ISSUE TITLE
polka.json() When?

### ISSUE THREAD

**Issue by ShayBox** [lukeed/polka#66]
Express has it's own parser so you don't have to use 3rd party middleware like body-parser, when will polka be adopting this.

**Comment by lukeed** [comment]
Hey,

The Express one _is_ `body-parser`, they just include it either an alias. See [here](https://expressjs.com/en/api.html#express.json).

It's the same story for `express.static` and `serve-static`

**Comment by lukeed** [comment]
That said, having a `@polka/json` package has been on my to-do list/backlog. 

I'll get to it in my coming push :)

Thanks!
