### ISSUE TITLE
Unable to test with supertest when subapps contains async route handler

### ISSUE THREAD

**Issue by motss** [lukeed/polka#72]
Currently encountering another issue where `async...await` does not work as expected with `supertest`. It works fine when:

1. changing `polka` to `express`, or
2. removing `async...await` to make route handler synchronous. 

However, this fails when I'm writing tests with `supertest`. For normal usage, there is no problem.

```js
const supertest = require('supertest');
const polka = require('polka');


const core = () => polka().post('/test', async (_, res) => { // Uncomment 'async' to see it works
  await Promise(yay => setTimeout(yay, 3e3)); // Uncomment 'await Promise(...)' to see it works

  res.end('OK');
});

const app = polka().use('/haha', core());

async function main() {
  const d = await supertest(app.handler)
    .post('/haha/test')
    .expect(200);

  return d.text;
}

main().then(console.log).catch(console.error);
```

**Comment by lukeed** [comment]
What's it doing? What's the unexpected part?

**Comment by motss** [comment]
By right, `d.text` should return 'OK'.

But the following code never get executed as long as it's an `async` function which is weird.

```js
async (_, res) => { // Uncomment 'async' to see it works
  await Promise(yay => setTimeout(yay, 3e3)); // Uncomment 'await Promise(...)' to see it works

  res.end('OK');
}
```

**Comment by lukeed** [comment]
Hey @motss, sorry for the delay on this one... work 🙈 

Just got a chance to check this out locally. You probably won't like this, but it works 😸 You had a simple typo in your code snippet:

```js
// await Promise(yay => setTimeout(yay, 3e3));
   await new Promise(yay => setTimeout(yay, 3e3)); // missing "new"
```

I've done the same thing a few times 😅 

Closing, since this does work~
