### ISSUE TITLE
Loading routes in separate file

### ISSUE THREAD

**Issue by oloier** [lukeed/polka#75]
This might be a stupid question, but I had trouble finding additional documentation. Do I need to pass the instance of polka in order to extend the routing to incorporate route definitions in another file? Do you have any examples?

**Comment by lukeed** [comment]
Hey, I'm not _entirely_ sure I understand the question, but you can always add new routes to the Polka instance, from anywhere. You just need access to the Polka instance itself.

For example:

```js
// routes/users.js

exports.param = 'userid';

exports.index = async (req, res) => {};
exports.show = async (req, res) => {};
exports.post = async (req, res) => {};
exports.put = [
  middleware1,
  middleware2,
  async (req, res) => {}
];
```

```js
// builder.js
const { readdirSync } = require('fs');
const { join, basename } = require('path');
const app = require('polka')();

const dir = join(__dirname, './routes');

const GET = ['index', 'show'];
const ROOT = ['index', 'post'];

readdirSync(dir).forEach(file => {
  const base = basename(file);
  const param = mod.param || 'id';
  const mod = require( join(dir, file) );

  for (let k in mod) {
    if (k == 'param') continue;
    let method = GET.includes(k) ? 'get' : k;
    let uri = ROOT.includes(k) ? base : `${base}/:${param}`;
    // add the route handler(s) 
    app.add(method, uri, mod[k]);
    // or:
    // app[method](uri, mod[k]);
    // ^ does not support multiple handlers
});
```

This will create all routes to the `/users` endpoint, and construct URLs (and methods) based on the export key name. It'd be equivalent to this:

```js
const app = require('polka')();

app.get('/users', async (req, res) => {});

app.get('/users/:userid', async (req, res) => {});

app.post('/users', async (req, res) => {});

app.put('/users/:userid', middleware1, middleware2, async (req, res) => {});
```

FWIW, you're much better off using a sub-application (or producing one similarly).

```js
const subapp = polka().get('/', ...).get('/:userid', ...).post('/', ...).put('/:userid', ...);

app.use('/users', subapp);
```

Hope that helps! Certainly possible. About half of my applications create routes dynamically thru some kind of file structure basis.

**Comment by oloier** [comment]
Certainly more than I had anticipated with that half-assed hastily posted question and non-issue. I appreciate all the information, that's a big help.

**Comment by lukeed** [comment]
Haha no problem, glad I was on the same page.
