### ISSUE TITLE
no res.redirect?

### ISSUE THREAD

**Issue by orefalo** [lukeed/polka#78]

**Comment by lukeed** [comment]
Not yet! On the agenda for 1.0 – see #5 🙌

**Comment by orefalo** [comment]
Think I figured it out

`
import * as encodeUrl from 'encodeurl';
...

res.writeHead(301, { Location: encodeUrl(myurl) });
res.end();
`


Thanks for the help, think I would have never find it out alone

**Comment by motss** [comment]
TIL. Thanks man.

**Comment by lukeed** [comment]
Oh, sorry guys. Didn't know there was a question for _how_ to do a redirect. Thought this was just a tracker for `res.redirect` to exist.

```js
let url = 'https://.../foo/bar';
let str = `Redirecting to ${url}`;

res.writeHead(302, {
	Location: url,
	'Content-Type': 'text/plain',
	'Content-Length': str.length
});

res.end(str);
```

This is pulled from one of my projects. It displays text in the browser for a moment – which isn't necessary but I chose to have it here.

**Comment by viktor89** [comment]
for compatibility with with other express middlewares like passport, a res.redirect function might also be a good idea

**Comment by viktor89** [comment]
should anyone stumble upon this, I solved my issue by added the method to the res object in a middleware like this:

`polka()
    .use(function(req, res, next) {
        res.redirect = location => {
            let str = `Redirecting to ${location}`;
            res.writeHead(302, {
                Location: location,
                'Content-Type': 'text/plain',
                'Content-Length': str.length,
            });
            res.end(str);
        };
        next();
    })`
