### ISSUE TITLE
is there any res.locals equivalent?

### ISSUE THREAD

**Issue by galuh1300d** [lukeed/polka#82]

**Comment by lukeed** [comment]
There isn't & I haven't decided if there should need to be in 1.0...

This is because `res.locals` is just an object. It only has special meaning in the context of view/template rendering. Polka won't have template rendering (by default) so I'm not sure how this should play out.

```js
polka()
  .use((req, res, next) => {
    res.locals = {}
    next();
  })
```

**Comment by makoven** [comment]
> It only has special meaning in the context of view/template rendering

Is it so? Express's type RequestHandler has a generic param Locals. And it is convenient to use it for creating typed middlewares that store values of a specific type in .locals, which can be used in the next middlewares. But type Middleware in @types/polka types just ignore this parameter

**Comment by lukeed** [comment]
It is not provided by default. The snippet in my last comment adds it manually.
