### ISSUE TITLE
help | cookieParser Implementation

### ISSUE THREAD

**Issue by nhtb** [lukeed/polka#83]
Hi! 

I've been struggling with cookie-parser implementation like express way. res.cookie is a function in express-example, but I got undefined. I'm not sure if I'm doing it wrong, please make comments about the code

const { handler } = app
    .use(
        helmet(),
        NODE_ENV === 'development' && cors(),
        bodyParser.json(),
        // bodyParser.urlencoded({ extended: true }),
        cookieParser(),
        cookieSession({
            name: 'trytry',
            secret: key,
            cookie: {
                secure: true,
                httpOnly: true,
                domain: 'localhost',
                path: '/asd',
                expires: new Date(Date.now() + 60 * 60 * 1000)
            }
        }),
        NODE_ENV === 'development' && serviceLogger()
    )
    .post('/tryout', (req, res) => {
        console.info('res.cookie: ', res.cookie); <<<<< got undefined
    });

Any help will be appreciated

**Comment by nhtb** [comment]
I've noticed missed something, solved

**Comment by lukeed** [comment]
Hey, sorry~! Have been busy at work this week. 

Sounds like you were able to solve it?

**Comment by nhtb** [comment]
No problem, I couldn't use res.cookie function which comes with cookie-parser.
It's undefined so I prefer to use setHeader('Set-Cookie' way

**Comment by lukeed** [comment]
Ah, yes. I would use something like `cookie` directly. You can check out their [example here](https://www.npmjs.com/package/cookie#example).
