### ISSUE TITLE
Double decoded req.query

### ISSUE THREAD

**Issue by lguzzon** [lukeed/polka#88]
In "next" branch, reg.query got decoded twice!!!
using this as server:
```javascript
const polka = require('polka')
polka()
.get('/', (req, res) => {
  res.end(JSON.stringify(req.query))
}).listen(8181, err => {
  if (err) throw err
  console.log(`Polka listening on port 8181`)
})
```
and "curling" it:
```bash
curl -v "http://127.0.0.1:8181/?i=TU10Z&n=smsitfix2&Q=%2b393383123549"
```
we got:
```json
{"i":"TU10Z","n":"smsitfix2","Q":" 393383123549"}
```
instead of:
```json
{"i":"TU10Z","n":"smsitfix2","Q":"+393383123549"}
```
may be @polka/url must not decode eagerly the url ...

**Comment by lukeed** [comment]
Ah, you're right. Thanks!

The `@olka/url` decodes it initially, and then passing `req.query` (string) thru `querystring.parse` will re-decode it again.

I'll push out a fix for this tonight :)

**Comment by lukeed** [comment]
Took the opportunity to basically rewrite `@polka/url` & made it [much faster](https://github.com/lukeed/polka/tree/next/packages/url/bench) in the process, haha 

Closing this since it's pertinent to `next` specifically, and there's now a new version up.

Thanks!
