### ISSUE TITLE
Calling Express 'super fast' is a bug

### ISSUE THREAD

**Issue by alexhultman** [lukeed/polka#9]
The readme clearly has issues. Express is clearly one of the most bloated and performance killing projects ever to see the light of dawn. It is up there among Socket.IO as top most overhyped pieces of garbage ever written by man kind. Don't use this marketing opportunity to spread misinformation, just say what you intended to say! It sucks and you know it.

**Comment by lukeed** [comment]
I'd prefer to win because of Polka's attributes rather than by disrespecting my competitors' work. 

Express is clearly widely used by many and is viable for them. Polka just has a different set of priorities and the freedom to rework things. To that point, Express was actually made _years_ ago and has been in a maintenance stage since then.

If you're on board with (and sounds like you are!) a framework doing less in exchange for faster performance, then welcome aboard! 🚂

**Comment by alexhultman** [comment]
Well you're never going to "win" by being humble. Every project, even those with obvious and severe performance issues - every single one - claims to be "fast" or even "fastest". How many of these "web frameworks" have been introduced in the last 6 months? 5? 10? 50? You'll be lost and forgotten about in 2 weeks with such a whimpy marketing. Express gains users not because it is good but because of how internet traffic grows exponentially once you hit a certain threshold - they did things in the very beginning just like Socket.IO and that's the only reason for them having such a massive following. Nobody cares to do the research, 99% will just follow blindly what the other guy does. You're never ever going to make a change by playing "the good guy" in an extremely overcrowded and sinister market.

**Comment by lukeed** [comment]
Haha, yeah maybe! I've been using Polka as is for almost a year already. Popularity is nice, sure, but this spawned from my API projects that are already in production. So it'd just be a bonus.

That said, I'll be more vocal once 1.0 comes, since accommodating others' use cases requires a little more thought.

Good guys do still win, though! It's just a matter of making the right amount of noise. 1.0 brings da noise

**Comment by lukeed** [comment]
FWIW, I'll definitely take a page out of your book and throw around charts and visuals 😃 That's always been the game plan, but I don't feel I can do that until I can guarantee API stability.

**Comment by alexhultman** [comment]
Slap a big fat bar chart in the faces of all your visitors, maybe even sprinkle some pie charts in there but keep it simple - most viewers have the attention span of a drugged down ADHD "special" kid. If you have the code to back it up you can, and should, market the hell out of it. Heck, buy one of those stock pictures of a "doctor" in white robe mixing semen in glass tubes if you can!

**Comment by lukeed** [comment]
Might avoid that last bit of advice 😉 Charts should be fine so long as I confine it to Node.js only

**Comment by alexhultman** [comment]
I just ran a bunch of different benchmarks. I'm impressed with the project - this is probably the only wrapper module I have seen written in JS that almost 100% captures the original performance of Node.js http module. Even "top contenders" :nauseated_face: like Aerojs and Fastify come way off with significant overhead.

I get somewhere around 28k req/seq with Aerojs and Fastify while "raw" Node.js is 35k and polka does 33k. That's really good job and I noticed I could pretty much just swap express for polka with no code changes?

Market those two parts: compatible with express (mostly) and close to zero overhead.

**Comment by lukeed** [comment]
Yup! Thank you 😄 For me, the performance difference is a lot cooler when you run all servers after sufficient warm-up. Native tops out at 43k for me, Polka at 41-42k, then Fastify leads the rest of the pack at 35k. I grew tired of overhead penalty too, especially here in the age of the microservice. 😆 

I have #8 in the works, which will make it a ~90% match with the Express API. I'll offer an opt-in package that (mostly?) mimics the response helpers for those who can't live without them, but honestly the native methods are totally fine.

This is the [list of differences](https://github.com/lukeed/polka#comparisons), in case you missed it.

Already "marketing" those two points -- the third being performance, of course. All points will be stronger come 1.0, although it fares really well already~

Just need a good weekend to wrap this all up!

**Comment by alexhultman** [comment]
This is roughly the marketing base I would use: https://github.com/alexhultman/polka

Short, easy to grasp, bold.

**Comment by lukeed** [comment]
Definitely! I definitely know where you're coming from in regards to all of this. The README, for now, is the stand-in until I get a website up. Definitely don't expect everyone to read the full readme, even tho that's what it's there for 😆 

Hate to keep telling you "1.0", but this is exactly that 😜 My 1.0 launch list has about a dozen items on it.

I'll ping you before the final draft goes out, how bah dat?

**Comment by alexhultman** [comment]
Did you just Danielle Bregoli me? xD

**Comment by lukeed** [comment]
Too much interweb today.

**Comment by girng** [comment]
One of Hultman's classic threads
