### ISSUE TITLE
Using HTTP Proxy Middleware

### ISSUE THREAD

**Issue by evanleck** [lukeed/polka#90]
Hi, I was wondering if you have an example of how to set up a proxying middleware for e.g. API calls. I've got [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) added to the base sapper-template but I imagine that the middleware ordering keeps it from ever getting run because Sapper is a global middleware.

Any help would be much appreciated, thank you!

**Comment by lukeed** [comment]
Hey, can you show me the sapper config you have?

**Comment by evanleck** [comment]
No problem, the `server.js` looks like this:

```js
import * as sapper from '@sapper/server';
import compression from 'compression';
import polka from 'polka';
import proxy from 'http-proxy-middleware';
import sirv from 'sirv';

const { PORT, NODE_ENV } = process.env;
const dev = NODE_ENV === 'development';

polka()
  .use(
    '/api',
    proxy({
      changeOrigin: true,
      logLevel: 'debug',
      target: 'https://ci-domain.com',
      pathRewrite: {
        '^/api/': ''
      }
    })
  )
  .use(
    compression({ threshold: 0 }),
    sirv('static', { dev }),
    sapper.middleware()
  )
  .listen(PORT, err => {
    if (err) console.log('error', err);
  });
```

**Comment by evanleck** [comment]
I think I solved my own problem! Moving the proxy into a global middleware and using its own context seems to have done the trick (or at least gotten me closer).

```js
import * as sapper from '@sapper/server';
import compression from 'compression';
import polka from 'polka';
import proxy from 'http-proxy-middleware';
import sirv from 'sirv';

const { PORT, NODE_ENV } = process.env;
const dev = NODE_ENV === 'development';

polka()
  .use(
    proxy('/api', {
      changeOrigin: true,
      logLevel: 'debug',
      target: 'https://ci-domain.com',
      pathRewrite: {
        '^/api': ''
      }
    }),
    compression({ threshold: 0 }),
    sirv('static', { dev }),
    sapper.middleware()
  )
  .listen(PORT, err => {
    if (err) console.log('error', err);
  });
```

**Comment by lukeed** [comment]
Ah, yeah! In current Polka, the order of global middleware matters.

Your original version would have worked too had you included `ignore` options inside Sapper, which would tell it to let the "/api" routes to fall through.

**Comment by evanleck** [comment]
Thanks for the tip on the ignore option, I hadn't seen that before!

**Comment by lukeed** [comment]
It might not be documented 😲but here: https://github.com/sveltejs/sapper/pull/326
