### ISSUE TITLE
should this work?

### ISSUE THREAD

**Issue by mgambill** [lukeed/polka#92]
Is this a bug or am I not understanding how routing works?
I have
```js
polka()
  .use(init)  
  .get('/', list)
  .use('/:id', findById)
  .get('/:id', single)
  .all('/:id', all)
```
For this route 
localhost/abc
*expect*
init, findById, single, all
*actual*
init, single 

* assume: all functions are calling next for this demo

I know i can write:
```js
.get('/:id', findById, single) // that works
```

**Comment by lukeed** [comment]
Hey,

In current stable release, it doesn't. However, in the `polka@next` release (the 1.0 candidate) it works as you expect.

My recommendation is that new applications should be using `@next` release. It's been heavily used and tested. I'm just finishing the rest of the supporting packages for 1.0 to finish.

Hope that helps!

**Comment by mgambill** [comment]
Thanks. I’ll update.
