### ISSUE TITLE
Can I take response body?

### ISSUE THREAD

**Issue by paz-raon** [lukeed/polka#95]
I want to log the processing-elapsed-time and response body.
Is there have something like a after-response-hook?

**Comment by lukeed** [comment]
Hey there,

Parsing the response body comes from a middleware like [`body-parser`](https://www.npmjs.com/package/body-parser) or Polka's recent [`@polka/parse`](https://www.npmjs.com/package/@polka/parse), which can be installed via `npm install @polka/parse@next` for now.

Not sure exactly what the first part of your question is to be honest. Are you trying to measure the elapsed time for parsing the request body, or trying to measure the elapsed time for the whole response cycle?

If the latter, there are a number of libraries that do this for you; like [`morgan`](http://npmjs.com/package/morgan) for example – and see [`examples/with-morgan`](https://github.com/lukeed/polka/tree/master/examples/with-morgan). Here's an [example from `sirv-cli`](https://github.com/lukeed/sirv/blob/master/packages/sirv-cli/boot.js#L48-L56) that does the same thing without any library (no Polka/middleware though).

I don't know of any parsers that specifically measure the time needed to parse the request body. You'd probably have to do that yourself by wrapping `body-parser` or `@polka/parse` directly.

Hope that helps!

**Comment by mgrybyk** [comment]
Hello @lukeed 

Are you going to proceed development of `@polka/parse`?

**Comment by lukeed** [comment]
Hey, yes! You can install now:

```
npm install --save @polka/parse@next
```

**Comment by mgrybyk** [comment]
thank you, waiting for an official release and sources to be published on github!

**Comment by lukeed** [comment]
It is both official and available on GitHub: https://github.com/lukeed/polka/tree/next/packages/parse

It's just not marked as "stable" since I want everything to be 1.0 at the same time. However, this module hasn't changed in a long time and should be considered as stable. I'm already using it in production

**Comment by mgrybyk** [comment]
ah, sorry, missed that!

Thanks a lot again!

**Comment by danawoodman** [comment]
@lukeed is there plains to mention how to parse the body of a request in the project readme? This seems likely something nearly all users would want to know about but I had to search issues to learn that this parse module exists and is recommended 😄

**Comment by lukeed** [comment]
Hi @danawoodman, please find my answer in this thread: https://github.com/lukeed/polka/issues/95#issuecomment-492763159

You can use `@polka/parse` or bring `body-parser` if you're used to that. They should be roughly the same

**Comment by danawoodman** [comment]
Sorry @lukeed, I did see that above, I guess I was just saying maybe it could also live in the README somewhere as right now I couldn't find this answer except in this ticket 😅

**Comment by lukeed** [comment]
When there's a site, it will be on there. As it is the readme is too long for most people to read it.
