### ISSUE TITLE
How to overwrite or remap one directory to another

### ISSUE THREAD

**Issue by paulocoghi** [lukeed/polka#98]
Is it possible to "remap" a directory to another using polka and sirv?

I created a [repository](https://github.com/paulocoghi/polka-test) to test the following code:

```js
// index.js
const polka = require('polka');
const sirv  = require('sirv');

const { PORT=3000 } = process.env;

polka()
  // Make "localhost:3000/components" to serve content from "public/compiled_components"
  .use('components', sirv('public/compiled_components'))

  // And everything else remains the same, on "public"
  .use(sirv('public'))

  .listen(PORT, err => {
    if (err) throw err;
    console.log(`Running on localhost:${PORT}`);
  });
```

My project has the following structure:

```
project
│   index.js
│
└───public
│   │
│   └───components (non compiled components)
│       │   component1.txt
│       │   component2.txt
│       │   ...
│   └───compiled_components (automatic compiled components, during development time)
│       │   component1.txt
│       │   component2.txt
│       │   ...
```

But, on the path `localhost:3000/components`, instead of serving the content of `public/compiled_components` it is still serving the content of `public/components`

**Comment by lukeed** [comment]
Sirv shares cache object for all files. I have a change for that incoming to not overwrite existing keys, but for now I think it'll work if you swap the sirv order. That way your compiled components are overwriting what you had inside uncompiled paths.

Really though, you should always be working from a single directory to make your life easy. It also means that your file server has to do less work, sirv or any

**Comment by paulocoghi** [comment]
> for now I think it'll work if you swap the sirv order

Even when swapping, strangely it isn't serving the content of `compiled_components`:

```js
polka()
  // This first
  .use(sirv('public'))

  // And this later
  .use('components', sirv('public/compiled_components'))

  .listen(PORT, err => {
    if (err) throw err;
    console.log(`Running on localhost:${PORT}`);
  });
```

**Comment by paulocoghi** [comment]
I am creating a development tool for a routing library to Svelte, with automatic reload when file changes.

I am trying to don't change the original `src` files of the developer and, instead, remapping only the directory of components, letting the remaining files untouched.

**Comment by lukeed** [comment]
```
.use(sirv(public), sirv(public/compiled))
```
if that doesn't work I have to check back later. I'm traveling today and on the road so I can't take a look right now

**Comment by paulocoghi** [comment]
Ok, thanks! I will take a look and try my best here :)

**Comment by lukeed** [comment]
You can also run one of the instances in dev mode. This isn't as ideal just because it skips the file caching, which means it will traverse the file system every time. Little more expensive, but that's exactly how other file servers work.

You would have to have the public one in development, But maybe even both

**Comment by paulocoghi** [comment]
Just to advance the subject, this (and only this) works:

```js
.use(sirv('public/compiled'), sirv('public'), sirv('public/compiled'))
```

But sharing cache object for all files is a **good thing** and is performance-wise. And I do not believe my use-case justifies a modification in `sirv`, since it is not normal.

**Comment by paulocoghi** [comment]
Your last response was the key. I was forgetting to enable development mode on this test, but I have done it on the library. Doh for me :sweat_smile:

**Comment by paulocoghi** [comment]
I am doing more tests now.

**Comment by paulocoghi** [comment]
It works!

```js
polka()
  .use(sirv('public/compiled', { dev: true }), sirv('public', { dev: true }))
```

**Comment by paulocoghi** [comment]
This also works:

```js
polka()
  .use(sirv('public/compiled', { dev: true }))
  .use(sirv('public', { dev: true }))
  .listen(PORT, err => {
    if (err) throw err;
    console.log(`Running on localhost:${PORT}`);
  });
```

**Comment by paulocoghi** [comment]
Only this does **not** work, but it isn't an issue for me:

```js
polka()
  .use('components', sirv('public/compiled/components', { dev: true }))
  .use(sirv('public', { dev: true }))
  .listen(PORT, err => {
    if (err) throw err;
    console.log(`Running on localhost:${PORT}`);
  });
```

**Comment by paulocoghi** [comment]
Thanks for everything! I believe `sirv` and `polka` must remain exactly as they already are. They are awesome!

**Comment by lukeed** [comment]
Great! The last sample will only work in the next version of Polka. The reason it isn't currently working is because stable polka is running use() before use('/foo')

**Comment by paulocoghi** [comment]
Thanks a lot!
